name: Daily Stats

on:
  schedule:
    - cron: '55 0,1,2,3,4,5,15,16,17,18,19,20,21,22,23 * * *' # 55mins after the hour every hour, 9:55am - 11:55pm CST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env: # shared for all steps
      POCKET_CASTS_PASSWORD: ${{ secrets.POCKET_CASTS_PASSWORD }}
      POCKET_CASTS_EMAIL: ${{ secrets.POCKET_CASTS_EMAIL }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.1'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Update daily stats
      run: bundle exec ruby main.rb
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add stats/ && git commit -m 'Update daily stats' || echo "No changes to commit"
        git push origin || echo "No changes to commit"
